# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

FIBONACCI = Enumerator.new do |y|
  next_two = [1,2]
  loop do
    y.yield next_two[0]
    next_two << next_two[0] + next_two[1]
    next_two.shift
  end
end

require 'test/unit'

class Problem2 < Test::Unit::TestCase
  def test_first_10_terms
    assert_equal [1,2,3,5,8,13,21,34,55,89], FIBONACCI.take(10)
  end

  def test_question
    result = FIBONACCI.
      take_while { |n| n < 4_000_000 }.
      select { |n| n % 2 == 0 }.
      inject { |sum, n| sum + n }
    assert_equal 4613732, result
  end
end
